// index.js
// Thin orchestrator. No business logic lives here.
//
// Both entry points - the cron trigger and the Bearer-authed /refresh
// endpoint - call runPipeline(). Exactly the same function, no exceptions.
// Everything a visitor sees is read live from R2, never from the deploy
// bundle.

import { IDEAS } from "./ideas-source.js";
import { pickIdea, dateKeyFor, isValidDateKey } from "./selection.js";
import { generateScript, countWords } from "./script.js";
import { narrate, formatDuration, WORDS_PER_MINUTE } from "./tts.js";
import { buildCoverSvg } from "./art.js";
import { buildRss, SHOW } from "./rss.js";
import { scoreIdea } from "./score.js";

const KEYS = {
  rotation: "state/rotation.json",
  manifest: "episodes/index.json",
  episode: (d) => `episodes/${d}.json`,
  audio: (d) => `audio/${d}.mp3`,
  art: (d) => `art/${d}.svg`,
  lock: (d) => `locks/run-${d}`
};

const LOCK_TTL_MS = 60_000;
const MANIFEST_LIMIT = 400;

// Regenerated content at a stable, date-keyed URL. NOT immutable - an
// immutable header would tell every podcast app to never re-check, so a
// forced re-run would silently never reach anyone who already fetched
// (spec gotcha 13).
const REVALIDATE = "public, max-age=86400, must-revalidate";
const SHORT = "public, max-age=60, must-revalidate";

// ---------------------------------------------------------------- helpers

function json(body, status = 200, headers = {}) {
  return new Response(JSON.stringify(body, null, 2), {
    status,
    headers: { "content-type": "application/json; charset=utf-8", "cache-control": SHORT, ...headers }
  });
}

/** Attribute-safe HTML escaping for the server-side meta-tag rewrite below. */
function escHtml(s) {
  return String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/** Every route that can trigger paid generation uses this. Not just the one
 *  you think of as "the" trigger - an unauthenticated generating route WILL
 *  get hit by crawlers and bill you for it (spec gotcha 12). */
function authorized(request, env) {
  const header = request.headers.get("Authorization") || "";
  const expected = `Bearer ${env.REFRESH_SECRET}`;
  if (!env.REFRESH_SECRET) return false;
  if (header.length !== expected.length) return false;
  let diff = 0;
  for (let i = 0; i < header.length; i++) diff |= header.charCodeAt(i) ^ expected.charCodeAt(i);
  return diff === 0;
}

async function readJson(env, key, fallback) {
  const obj = await env.PODCAST_BUCKET.get(key);
  if (!obj) return fallback;
  try {
    return await obj.json();
  } catch {
    return fallback;
  }
}

async function writeJson(env, key, value) {
  await env.PODCAST_BUCKET.put(key, JSON.stringify(value), {
    httpMetadata: { contentType: "application/json; charset=utf-8", cacheControl: SHORT }
  });
}

/** Conditional-write lock. Prevents a cron firing while a manual test is
 *  mid-run from corrupting the rotation state (spec gotcha 14). */
async function acquireLock(env, dateKey) {
  const existing = await env.PODCAST_BUCKET.get(KEYS.lock(dateKey));
  if (existing) {
    const started = Number(await existing.text());
    if (Date.now() - started < LOCK_TTL_MS) return false;
    await env.PODCAST_BUCKET.delete(KEYS.lock(dateKey));
  }
  const put = await env.PODCAST_BUCKET.put(KEYS.lock(dateKey), String(Date.now()), {
    onlyIf: { etagDoesNotMatch: "*" }
  });
  return put !== null;
}

async function releaseLock(env, dateKey) {
  try {
    await env.PODCAST_BUCKET.delete(KEYS.lock(dateKey));
  } catch (err) {
    console.log(`lock release failed for ${dateKey}: ${err.message}`);
  }
}

// --------------------------------------------------------------- pipeline

/**
 * The one function both entry points call.
 * @param {object} env
 * @param {object} opts { dateKey?: string, force?: boolean }
 */
export async function runPipeline(env, opts = {}) {
  const startedAt = Date.now();
  const dateKey = opts.dateKey || dateKeyFor(new Date());

  if (!isValidDateKey(dateKey)) {
    return { ok: false, error: `invalid date "${dateKey}", expected YYYY-MM-DD` };
  }

  const existing = await env.PODCAST_BUCKET.get(KEYS.episode(dateKey));
  if (existing && !opts.force) {
    return { ok: true, skipped: "already generated", date: dateKey, episode: await existing.json() };
  }

  if (!(await acquireLock(env, dateKey))) {
    return { ok: false, error: "another run is in progress for this date", date: dateKey };
  }

  try {
    // 1. Pick the topic. Usage tracked in R2, never in code.
    const rotation = await readJson(env, KEYS.rotation, { used: [], recentCategories: [] });
    const { idea, state, cycleReset } = pickIdea(dateKey, rotation);

    // Computed entirely from vetted pool fields - never regenerated by the
    // model, so the same idea always scores the same (score.js).
    const score = scoreIdea(idea);

    // 2. Generate the script. Word count computed in code from real text.
    const script = await generateScript(env, idea, dateKey);

    // 3. Generate the audio. Speech gets the version with SSML pause tags;
    // the transcript and word count stay on the clean version - a reader
    // should never see "<break time=...>" in the archived text.
    const audio = await narrate(env, script.narrationForSpeech, script.wordCount);

    // 4. Optional extras. Must never block the episode.
    let artKey = null;
    try {
      const svg = buildCoverSvg(idea, dateKey);
      await env.PODCAST_BUCKET.put(KEYS.art(dateKey), svg, {
        httpMetadata: { contentType: "image/svg+xml", cacheControl: REVALIDATE }
      });
      artKey = KEYS.art(dateKey);
    } catch (err) {
      console.log(`cover art failed for ${dateKey}, shipping without it: ${err.message}`);
    }

    // 5. Write everything. This is the step that has to succeed.
    await env.PODCAST_BUCKET.put(KEYS.audio(dateKey), audio.audio, {
      httpMetadata: { contentType: "audio/mpeg", cacheControl: REVALIDATE }
    });

    const episode = {
      date: dateKey,
      ideaId: idea.id,
      title: idea.title,
      category: idea.category,
      thesis: idea.thesis,
      customer: idea.customer,
      competitors: idea.competitors,
      complexity: idea.complexity,
      complexityWhy: idea.complexityWhy,
      capital: idea.capital,
      firstNinety: idea.firstNinety,
      claudeRole: idea.claudeRole,
      moat: idea.moat,
      sourceNotes: idea.sourceNotes,
      opportunityType: idea.opportunityType,
      score,
      sections: script.sections,
      bearCase: script.sections.bearCase,
      assumptions: script.sections.assumptions,
      verdict: script.sections.verdict,
      transcript: script.narration,
      pullQuote: script.sections.pullQuote || idea.thesis,
      tags: script.sections.tags || [],
      wordCount: script.wordCount,
      pitchWordCount: script.pitchWordCount,
      tightened: script.retried,
      overBudget: script.overBudget,
      durationSeconds: audio.estimatedDurationSeconds,
      durationLabel: formatDuration(audio.estimatedDurationSeconds),
      wordsPerMinuteUsed: Number(env.WORDS_PER_MINUTE || WORDS_PER_MINUTE),
      audioBytes: audio.byteLength,
      audioBlocks: audio.blocks,
      narratorSpeed: audio.speed,
      artUrl: artKey ? `/art/${dateKey}.svg` : null,
      audioUrl: `/audio/${dateKey}.mp3`,
      generatedAt: new Date().toISOString(),
      generationMs: Date.now() - startedAt
    };

    await writeJson(env, KEYS.episode(dateKey), episode);

    const manifest = await readJson(env, KEYS.manifest, { episodes: [] });
    const summary = {
      date: dateKey,
      title: episode.title,
      category: episode.category,
      thesis: episode.thesis,
      pullQuote: episode.pullQuote,
      complexity: episode.complexity,
      capitalTotal: episode.capital.total,
      durationSeconds: episode.durationSeconds,
      durationLabel: episode.durationLabel,
      audioBytes: episode.audioBytes,
      tags: episode.tags,
      score: episode.score.overall,
      band: episode.score.band,
      opportunityType: episode.opportunityType,
      verdict: episode.verdict
    };
    const episodes = [summary, ...manifest.episodes.filter((e) => e.date !== dateKey)]
      .sort((a, b) => (a.date < b.date ? 1 : -1))
      .slice(0, MANIFEST_LIMIT);

    await writeJson(env, KEYS.manifest, { episodes, updatedAt: new Date().toISOString() });
    await writeJson(env, KEYS.rotation, state);

    return {
      ok: true,
      date: dateKey,
      cycleReset,
      remainingInPool: state.remaining,
      episode: {
        ...summary,
        wordCount: episode.wordCount,
        pitchWordCount: episode.pitchWordCount,
        tightened: episode.tightened,
        overBudget: episode.overBudget,
        audioUrl: episode.audioUrl,
        artUrl: episode.artUrl,
        generationMs: episode.generationMs
      }
    };
  } catch (err) {
    console.log(`pipeline failed for ${dateKey}: ${err.stack || err.message}`);
    return { ok: false, date: dateKey, error: err.message };
  } finally {
    await releaseLock(env, dateKey);
  }
}

// ----------------------------------------------------------------- serving

/** Range support is required by Apple Podcasts' playback stack
 *  (spec gotcha 8). "Plays in a browser audio tag" proves nothing. */
async function serveObject(env, key, contentType, request) {
  const range = request.headers.get("Range");

  if (range) {
    const match = /^bytes=(\d*)-(\d*)$/.exec(range.trim());
    if (match) {
      const head = await env.PODCAST_BUCKET.head(key);
      if (!head) return new Response("Not found", { status: 404 });

      const size = head.size;
      let start = match[1] === "" ? null : Number(match[1]);
      let end = match[2] === "" ? null : Number(match[2]);

      if (start === null && end !== null) {
        start = Math.max(size - end, 0);
        end = size - 1;
      } else {
        if (start === null) start = 0;
        if (end === null || end >= size) end = size - 1;
      }

      if (start >= size || start > end) {
        return new Response("Range not satisfiable", {
          status: 416,
          headers: { "content-range": `bytes */${size}` }
        });
      }

      const obj = await env.PODCAST_BUCKET.get(key, {
        range: { offset: start, length: end - start + 1 }
      });
      if (!obj) return new Response("Not found", { status: 404 });

      return new Response(obj.body, {
        status: 206,
        headers: {
          "content-type": contentType,
          "content-range": `bytes ${start}-${end}/${size}`,
          "content-length": String(end - start + 1),
          "accept-ranges": "bytes",
          "cache-control": REVALIDATE,
          etag: head.httpEtag
        }
      });
    }
  }

  const obj = await env.PODCAST_BUCKET.get(key);
  if (!obj) return new Response("Not found", { status: 404 });

  return new Response(obj.body, {
    headers: {
      "content-type": contentType,
      "content-length": String(obj.size),
      "accept-ranges": "bytes",
      "cache-control": REVALIDATE,
      etag: obj.httpEtag
    }
  });
}

// ------------------------------------------------------------------ worker

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    const path = url.pathname;
    const origin = env.PUBLIC_ORIGIN || url.origin;

    // Manual trigger. Bearer only - never a query-string secret.
    if (path === "/refresh") {
      if (!authorized(request, env)) {
        return json({ ok: false, error: "unauthorized" }, 401);
      }
      const asOf = url.searchParams.get("asOf");
      const force = url.searchParams.get("force") === "1";
      const result = await runPipeline(env, { dateKey: asOf || undefined, force });
      return json(result, result.ok ? 200 : 500);
    }

    // Diagnostics. Also authed - it reveals rotation state.
    if (path === "/status") {
      if (!authorized(request, env)) return json({ ok: false, error: "unauthorized" }, 401);
      const rotation = await readJson(env, KEYS.rotation, { used: [], recentCategories: [] });
      const manifest = await readJson(env, KEYS.manifest, { episodes: [] });
      return json({
        ok: true,
        poolSize: IDEAS.length,
        used: rotation.used.length,
        remaining: IDEAS.length - rotation.used.length,
        recentCategories: rotation.recentCategories,
        episodeCount: manifest.episodes.length,
        latest: manifest.episodes[0] || null,
        wordsPerMinute: Number(env.WORDS_PER_MINUTE || WORDS_PER_MINUTE)
      });
    }

    if (path === "/api/episodes.json") {
      const manifest = await readJson(env, KEYS.manifest, { episodes: [] });
      return json({ show: { title: SHOW.title, subtitle: SHOW.subtitle }, ...manifest });
    }

    const episodeMatch = /^\/api\/episode\/(\d{4}-\d{2}-\d{2})\.json$/.exec(path);
    if (episodeMatch) {
      const ep = await readJson(env, KEYS.episode(episodeMatch[1]), null);
      return ep ? json(ep) : json({ ok: false, error: "no episode for that date" }, 404);
    }

    const audioMatch = /^\/audio\/(\d{4}-\d{2}-\d{2})\.mp3$/.exec(path);
    if (audioMatch) return serveObject(env, KEYS.audio(audioMatch[1]), "audio/mpeg", request);

    const artMatch = /^\/art\/(\d{4}-\d{2}-\d{2})\.svg$/.exec(path);
    if (artMatch) return serveObject(env, KEYS.art(artMatch[1]), "image/svg+xml", request);

    if (path === "/cover/show.jpg") return serveObject(env, "cover/show.jpg", "image/jpeg", request);

    if (path === "/rss.xml" || path === "/feed.xml") {
      const manifest = await readJson(env, KEYS.manifest, { episodes: [] });
      return new Response(buildRss(manifest.episodes, origin), {
        headers: {
          "content-type": "application/rss+xml; charset=utf-8",
          "cache-control": SHORT
        }
      });
    }

    if (path === "/transcript.txt" || /^\/transcript\/\d{4}-\d{2}-\d{2}\.txt$/.test(path)) {
      const d = path.split("/").pop().replace(".txt", "");
      const ep = await readJson(env, KEYS.episode(d), null);
      if (!ep) return new Response("Not found", { status: 404 });
      return new Response(`${ep.title}\n${ep.date}\n\n${ep.transcript}\n`, {
        headers: { "content-type": "text/plain; charset=utf-8", "cache-control": REVALIDATE }
      });
    }

    // Bare date path (/2026-08-27) - additive alongside the existing hash
    // routing (#2026-08-27), not a replacement. Hash routing stays exactly
    // as it was for in-page archive navigation; this path exists only so a
    // shared link's <meta> tags reflect the actual episode when a social
    // crawler fetches it - crawlers don't run JS and don't see #fragments,
    // so client-side rendering alone can never produce a correct preview
    // here. If no episode exists for the date, fall through to the normal
    // SPA below rather than 404 - the client already handles "no brief for
    // this date" gracefully.
    const datePathMatch = /^\/(\d{4}-\d{2}-\d{2})$/.exec(path);
    if (datePathMatch) {
      const ep = await readJson(env, KEYS.episode(datePathMatch[1]), null);
      if (ep) {
        const assetRes = await env.ASSETS.fetch(new Request(`${origin}/`, request));
        let html = await assetRes.text();
        const title = `${ep.title} - Innovation Daily`;
        const desc = `${ep.pullQuote || ep.thesis} Score ${ep.score?.overall ?? "-"} of 100, ${ep.capital.total.toLocaleString("en-US")} dollars to start.`;
        const pageUrl = `${origin}/${ep.date}`;

        html = html
          .replace(/<title>[^<]*<\/title>/, `<title>${escHtml(title)}</title>`)
          .replace(/(<meta property="og:title" content=")[^"]*(")/, `$1${escHtml(ep.title)}$2`)
          .replace(/(<meta property="og:description" content=")[^"]*(")/, `$1${escHtml(desc)}$2`)
          .replace(/(<meta property="og:url" content=")[^"]*(")/, `$1${escHtml(pageUrl)}$2`)
          .replace(/(<meta name="twitter:title" content=")[^"]*(")/, `$1${escHtml(ep.title)}$2`)
          .replace(/(<meta name="twitter:description" content=")[^"]*(")/, `$1${escHtml(desc)}$2`);
          // og:image / twitter:image intentionally left pointing at the
          // static show poster (/cover/show.jpg) - it's a guaranteed
          // raster image. Per-episode preview art would need a raster
          // (not SVG) generation step this pipeline doesn't have yet.

        return new Response(html, {
          headers: { "content-type": "text/html; charset=utf-8", "cache-control": SHORT }
        });
      }
    }

    // Everything else falls through to the static single-page site, which
    // fetches its own data from the JSON API above.
    return env.ASSETS.fetch(request);
  },

  async scheduled(event, env, ctx) {
    ctx.waitUntil(
      (async () => {
        const result = await runPipeline(env);
        console.log(`cron run: ${JSON.stringify(result)}`);
      })()
    );
  }
};
